version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=ordway
      - POSTGRES_PASSWORD=ordway
      - POSTGRES_DB=ordway_development
  web:
    build: .
    tty: true
    # user: "1000:1000"
    stdin_open: true
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - '.env'
  
